spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minfin
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    openfeign:
      client:
        config:
          bank:
            url: https://api.nbrb.by/bic

server:
  port: 8080

jwt:
  secret: "your-256-bit-secret-key-here-1234567890"
  expiration: 3600
